StoreFront2.UI.MVC/Controllers/FitsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using StoreFront2.DATA.EF;

namespace StoreFront2.UI.MVC.Controllers
{
    [Authorize]
    public class FitsController : Controller
    {
        private StoreFrontEntities db = new StoreFrontEntities();

        // GET: Fits
        [AllowAnonymous]//ANYONE CAN SEE DETAILS
        public ActionResult Index()
        {
            return View(db.Fits.ToList());
        }

        // GET: Fits/Details/5
        [AllowAnonymous]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Fit fit = db.Fits.Find(id);
            if (fit == null)
            {
                return HttpNotFound();
            }
            return View(fit);
        }

        // GET: Fits/Create
        [Authorize(Roles = "Admin")]//ADMIN ONLY
        public ActionResult Create()
        {
            return View();
        }

        // POST: Fits/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = "Admin")]//ADMIN ONLY
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "FitID,FitName")] Fit fit)
        {
            if (ModelState.IsValid)
            {
                db.Fits.Add(fit);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(fit);
        }

        // GET: Fits/Edit/5
        [Authorize(Roles = "Admin, Sales")]//ADMIN and SALES ONLY
        public ActionResult Edit(int? id)

        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Fit fit = db.Fits.Find(id);
            if (fit == null)
            {
                return HttpNotFound();
            }
            return View(fit);
        }

        // POST: Fits/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin, Sales")]//ADMIN and SALES only
        public ActionResult Edit([Bind(Include = "FitID,FitName")] Fit fit)
        {
            if (ModelState.IsValid)
            {
                db.Entry(fit).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(fit);
        }

        // GET: Fits/Delete/5
        [Authorize(Roles = "Admin")]//ADMIN ONLY
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Fit fit = db.Fits.Find(id);
            if (fit == null)
            {
                return HttpNotFound();
            }
            return View(fit);
        }

        // POST: Fits/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]//ADMIN ONLY
        public ActionResult DeleteConfirmed(int id)
        {
            Fit fit = db.Fits.Find(id);
            db.Fits.Remove(fit);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

StoreFront2.UI.MVC/Controllers/MaterialsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using StoreFront2.DATA.EF;

namespace StoreFront2.UI.MVC.Controllers
{
    public class MaterialsController : Controller
    {
        private StoreFrontEntities db = new StoreFrontEntities();

        // GET: Materials
        public ActionResult Index()
        {
            return View(db.Materials.ToList());
        }

        // GET: Materials/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Material material = db.Materials.Find(id);
            if (material == null)
            {
                return HttpNotFound();
            }
            return View(material);
        }

        // GET: Materials/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Materials/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaterialID,MaterialName")] Material material)
        {
            if (ModelState.IsValid)
            {
                db.Materials.Add(material);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(material);
        }

        // GET: Materials/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Material material = db.Materials.Find(id);
            if (material == null)
            {
                return HttpNotFound();
            }
            return View(material);
        }

        // POST: Materials/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaterialID,MaterialName")] Material material)
        {
            if (ModelState.IsValid)
            {
                db.Entry(material).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(material);
        }

        // GET: Materials/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Material material = db.Materials.Find(id);
            if (material == null)
            {
                return HttpNotFound();
            }
            return View(material);
        }

        // POST: Materials/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Material material = db.Materials.Find(id);
            db.Materials.Remove(material);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

StoreFront2.UI.MVC/Controllers/SuppliersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using StoreFront2.DATA.EF;

namespace StoreFront2.UI.MVC.Controllers
{
    public class SuppliersController : Controller
    {
        private StoreFrontEntities db = new StoreFrontEntities();

        // GET: Suppliers
        public ActionResult Index()
        {
            return View(db.Suppliers.ToList());
        }

        // GET: Suppliers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Supplier supplier = db.Suppliers.Find(id);
            if (supplier == null)
            {
                return HttpNotFound();
            }
            return View(supplier);
        }

        // GET: Suppliers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Suppliers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "SupplierID,CompanyName,City,State,Phone")] Supplier supplier)
        {
            if (ModelState.IsValid)
            {
                db.Suppliers.Add(supplier);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(supplier);
        }

        // GET: Suppliers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Supplier supplier = db.Suppliers.Find(id);
            if (supplier == null)
            {
                return HttpNotFound();
            }
            return View(supplier);
        }

        // POST: Suppliers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "SupplierID,CompanyName,City,State,Phone")] Supplier supplier)
        {
            if (ModelState.IsValid)
            {
                db.Entry(supplier).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(supplier);
        }

        // GET: Suppliers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Supplier supplier = db.Suppliers.Find(id);
            if (supplier == null)
            {
                return HttpNotFound();
            }
            return View(supplier);
        }

        // POST: Suppliers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Supplier supplier = db.Suppliers.Find(id);
            db.Suppliers.Remove(supplier);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

StoreFront2.UI.MVC/Controllers/TypesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using StoreFront2.DATA.EF;
using Type = StoreFront2.DATA.EF.Type;

namespace StoreFront2.UI.MVC.Controllers
{
    public class TypesController : Controller
    {
        private StoreFrontEntities db = new StoreFrontEntities();

        // GET: Types
        public ActionResult Index()
        {
            return View(db.Types.ToList());
        }

        // GET: Types/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Type type = db.Types.Find(id);
            if (type == null)
            {
                return HttpNotFound();
            }
            return View(type);
        }

        // GET: Types/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Types/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "TypeID,TypeName")] Type type)
        {
            if (ModelState.IsValid)
            {
                db.Types.Add(type);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(type);
        }

        // GET: Types/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Type type = db.Types.Find(id);
            if (type == null)
            {
                return HttpNotFound();
            }
            return View(type);
        }

        // POST: Types/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "TypeID,TypeName")] Type type)
        {
            if (ModelState.IsValid)
            {
                db.Entry(type).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(type);
        }

        // GET: Types/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Type type = db.Types.Find(id);
            if (type == null)
            {
                return HttpNotFound();
            }
            return View(type);
        }

        // POST: Types/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Type type = db.Types.Find(id);
            db.Types.Remove(type);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

StoreFront2.UI.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,500,600,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Rokkitt:100,300,400,700" rel="stylesheet">


    <!-- Animate.css -->
    <link rel="stylesheet" href="~/Content/css/animate.css">
    <!-- Icomoon Icon Fonts-->
    <link rel="stylesheet" href="~/Content/css/icomoon.css">
    <!-- Ion Icon Fonts-->
    <link rel="stylesheet" href="~/Content/css/ionicons.min.css">
    <!-- Bootstrap  -->
    <link rel="stylesheet" href="~/Content/css/bootstrap.min.css">
    <!-- Magnific Popup -->
    <link rel="stylesheet" href="~/Content/css/magnific-popup.css">
    <!-- Flexslider  -->
    <link rel="stylesheet" href="~/Content/css/flexslider.css">
    <!-- Owl Carousel -->
    <link rel="stylesheet" href="~/Content/css/owl.carousel.min.css">
    <link rel="stylesheet" href="~/Content/css/owl.theme.default.min.css">
    <!--jQuery UI below:-->
    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">

    <!-- Date Picker -->
    <link rel="stylesheet" href="~/Content/css/bootstrap-datepicker.css">
    <!-- Flaticons  -->
    <link rel="stylesheet" href="~/Content/fonts/flaticon/font/flaticon.css">
    <!--Carousel Below added 3-27-2021-->
    <link href="~/Content/css/css/jquery-gallery.css" rel="stylesheet" />


    @RenderSection("datatablesCSS", required: false)

    <!-- Theme style  -->
    <link rel="stylesheet" href="~/Content/css/style.css">

</head>
<body>
    <div class="colorlib-loader"></div>
    <div id="page">
        <div class="sale">
            <div class="container">
                <div class="row">
                    <div class="col-sm-8 offset-sm-2 text-center">
                        <div class="row">
                            <div class="owl-carousel2">
                                <div class="item">
                                    <div class="col">
                                        <h3>
                                            <a href="@Url.Action("Index", "Home")">The Luminary Body Jewelery</a>
                                        </h3>
                                    </div>
                                </div>
                                <div class="item">
                                    <div class="col">
                                        <h3><a href="@Url.Action("Store","Home")">Exotic pieces. Quality Materials. Just For You.</a></h3>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <nav class="colorlib-nav" role="navigation">
            <div class="top-menu">
                <div class="container">
                    <div class="row header" id="landing-header" style="">
                        <div class="col-sm-7 col-md-9">
                            <div id="colorlib-logo">
                                <a href="@Url.Action("Index","Home")">
                                    <img src="~/Content/images/TheLuminaryLogo.png" />
                                </a>
                                <form action="#" class="search-wrap">
                                    <div class="form-group">
                                        <input type="search" class="form-control search" placeholder="Search">
                                        <button class="btn btn-primary submit-search text-center" type="submit"><i class="icon-search"></i></button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12 text-left menu-1" id="mainNav">
                            <ul>

                                <li>@Html.ActionLink("Home", "Index", "Home")</li>
                                <li class="has-dropdown">
                                    <a href="@Url.Action("Index","Jeweleries")">Jewelery</a>
                                    <ul class="dropdown">
                                        <li><a href="@Url.Action("Index","Types")">Styles</a></li>
                                        <li><a href="@Url.Action("Index","Fits")">Sizes</a></li>
                                        <li><a href="@Url.Action("Index", "Materials")">Materials</a></li>
                                        <li><a href="@Url.Action("Index", "Suppliers")">Suppliers</a></li>
                                    </ul>
                                </li>
                                <li>@Html.ActionLink("Contact", "Contact", "Home")</li>

                                <li> @Html.Partial("_LoginPartial")</li>

                                @if (Request.IsAuthenticated && User.IsInRole("Admin"))
                                {
                                    <li class="">@Html.ActionLink("Roles Admin", "Index", "RolesAdmin")</li>
                                    <li class="">@Html.ActionLink("Users Admin", "Index", "UsersAdmin")</li>
                                }
                                @{
                                    //make total items variable
                                    int totalItems = 0;
                                    if (Session["cart"] != null && ((Dictionary<int, StoreFront2.UI.MVC.Models.CartItemViewModel>)Session["cart"]).Count > 0)
                                    {
                                        //we have to unbox session. Then know the total items in cart.
                                        Dictionary<int, StoreFront2.UI.MVC.Models.CartItemViewModel> cart = (Dictionary<int, StoreFront2.UI.MVC.Models.CartItemViewModel>)Session["cart"];//casting session at "cart" to dictionary.
                                                                                                                                                                                          //now foreach
                                        foreach (var item in cart)
                                        {
                                            totalItems += item.Value.Qty;
                                            //reassignment of totalItems.
                                        }
                                    }
                                }
                                <li class="cart">
                                    <a href="@Url.Action("Index", "ShoppingCart")">
                                        <i class="icon-shopping-cart">
                                        </i> Cart [@totalItems]
                                    </a>

                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </nav>
    </div>
    @*<div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>*@
    @*</div>*@


    <div class="container">
        @* AJAX DELETE STEP 8 - Message Container *@
        <div id="MessageDisplay" class="row">
            <div class="col-md-10 col-md-offset-1" id="MessageContent"></div>
        </div>
    </div>
    @* Step 9 is on the Jewelery controller. *@


    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - The Luminary Body Jewelery</p>
        </footer>
    </div>
    <h2 class="text-center">Trusted Partners</h2>

    <div class="row partners">
        <div class="col partner-col text-center">

            <img src="~/Content/images/Supplier1.png" />
        </div>
        <div class="col partner-col text-center">

            <img src="~/Content/images/Supplier2.png" />
        </div>
        <div class="col partner-col text-center">

            <img src="~/Content/images/Supplier3.png" />
        </div>

    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

    <!-- jQuery -->
    <script src="~/Content/js/jquery.min.js"></script>
    <!-- popper -->
    <script src="~/Content/js/popper.min.js"></script>
    <!-- bootstrap 4.1 -->
    <script src="~/Content/js/bootstrap.min.js"></script>
    <!-- jQuery easing -->
    <script src="~/Content/js/jquery.easing.1.3.js"></script>
    <!-- Waypoints -->
    <script src="~/Content/js/jquery.waypoints.min.js"></script>
    <!-- Flexslider -->
    <script src="~/Content/js/jquery.flexslider-min.js"></script>
    <!-- Owl carousel -->
    <script src="~/Content/js/owl.carousel.min.js"></script>
    <!-- Magnific Popup -->
    <script src="~/Content/js/jquery.magnific-popup.min.js"></script>
    <script src="~/Content/js/magnific-popup-options.js"></script>
    <!-- Date Picker -->
    <script src="~/Content/js/bootstrap-datepicker.js"></script>
    <!-- Stellar Parallax -->
    <script src="~/Content/js/jquery.stellar.min.js"></script>
    <!-- Main -->
    <script src="~/Content/js/main.js"></script>
    <script src="//cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js"></script>
    <!--AJAX STEP 1: jQuery UI below-->
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    <script src="~/Content/js/jquery-gallery.js"></script>
</body>
</html>

StoreFront2.UI.MVC/Views/Shared/_OriginalLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>

                    @if (Request.IsAuthenticated && User.IsInRole("Admin")) {
                        <li>@Html.ActionLink("RolesAdmin", "Index", "RolesAdmin")</li>
                        <li>@Html.ActionLink("UsersAdmin", "Index", "UsersAdmin")</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>