StoreFront2.UI.MVC/Models/ContactViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace StoreFrontJordan.MVC.UI.Models
{
    public class ContactViewModel
    {

        [Required(ErrorMessage = "* Name is required.")]
        public string Name { get; set; }

        public string Subject { get; set; }

        [Required(ErrorMessage = "* Message is required.")]
        [UIHint("MultiLineText")]

        public string Message { get; set; }

        [Required(ErrorMessage = "* Email is required.")]
        [EmailAddress(ErrorMessage = "* Please make sure your Email is in the proper formatting.")]
        [Display(Name = "Your Email")]
        public string EmailAddress { get; set; }

    }
}

StoreFront2.UI.MVC/Controllers/HomeController.cs
using StoreFrontJordan.MVC.UI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;

namespace StoreFrontJordan.MVC.UI.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Store()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {


            return View();
        }
        public ActionResult Checkout()
        {


            return View();
        }

        public ActionResult Cart()
        {


            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Contact(ContactViewModel cvm)
        {
            #region Email Notes
            //Usings TYPICALLY required for sending mail.
            //System.Net - Access to provide credentials for the SMTP server (username password port)
            //System.Net.Mail - Access to Mail Message class and methods associated.
            //Models folder (where our viewModel lives)

            //information required to send the email:
            //SMTP Server Name - mail.domain.ext
            //Email UserName (created at smarterASP)
            //Email Password (if you keep the default with SmarterASP, it is the same as your acct login pw)
            //port numbers - only need to be defined if your attempt to send mail fails (because of access)
            //Default (if not declared) is 25, alternate (must define) is 8889.
            #endregion

            //before we attempt to do anything with the instance of our model class
            //we want make sure it passes model validation
            if (!ModelState.IsValid)
            //ModelState.IsValid == false)
            {
                //if the object doesnt pass validation, send back the form WITH the object
                //that will repopulate the form AND show the validation errors.
                return View(cvm);
            }

            //this only executes if the form/object passes model validation
            //build the email message (this is what YOU will see when a user sends an email
            //from YOUR website.
            string message = $"You have received an email from {cvm.Name} with a subject of " +
                $"{(cvm.Subject == null ? "Email From SITENAME" : cvm.Subject)}. Please respond to " +
                $"{cvm.EmailAddress} with your response to the following message:<br /><br />" +
                $"{cvm.Message}";

            //build the MailMesage Object
            //FQ ctor to use: FROM, To, Subject, Message
            MailMessage mm = new MailMessage("admin@JordanHickman.com", "jdhickman816@outlook.com", cvm.Subject,//update
                message);

            //MailMessage properties
            mm.IsBodyHtml = true;

            //priority is not required, if you are going to leave at normal or low, just omit.
            mm.Priority = MailPriority.High;

            //update the reply to go to the end user instead of your admin Account at the website
            mm.ReplyToList.Add(cvm.EmailAddress);


            //Send the email
            SmtpClient client = new SmtpClient("mail.JordanHickman.com");//update
            //port 25 is the default. If your email does not send within 4 hours
            //consider changing the port value to be 8889;
            //client.Port = 8889;

            //client credentials
            client.Credentials = new NetworkCredential("admin@JordanHickman.com", "HmtU7APYMus_");//update

            //attempt to send the email
            //it is possible that the mail server is unavailable, in that case we do want to use
            //exception handling to care for mail message sending failure
            try
            {
                //attempt to send email
                client.Send(mm);
            }
            catch (Exception ex)
            {
                ViewBag.CustomerMessage = $"We're sorry your request could not be completed at this time. " +
                    $"Please try again later. Error Message:<br /><br />{ex.StackTrace}.";
                //stack trace is more for admin (recreate the problem) and should be encapsulated
                //in the an if(user.isinrole("admin") in the view.
                return View(cvm);
            }

            //if all goes well, return a view that displays a confirmation message - optionally,
            //you could provide the email content that they provided.
            return View("EmailConfirmation", cvm);
            //return RedirectToAction("Index");
        }

    }
}

StoreFront2.UI.MVC/Controllers/JeweleriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using StoreFront2.DATA.EF;
using System.Drawing;
using StoreFront2.UI.MVC.Utilities;
using StoreFront2.UI.MVC.Models;

namespace StoreFront2.UI.MVC.Controllers
{
    public class JeweleriesController : Controller
    {
        private StoreFrontEntities db = new StoreFrontEntities();

        // GET: Jeweleries
        public ActionResult Index()
        {
            var jeweleries = db.Jeweleries.Include(j => j.Fit).Include(j => j.InvStatu).Include(j => j.Material).Include(j => j.Supplier).Include(j => j.Type);
            return View(jeweleries.ToList());
        }

        // GET: Jeweleries/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Jewelery jewelery = db.Jeweleries.Find(id);
            if (jewelery == null)
            {
                return HttpNotFound();
            }
            return View(jewelery);
        }

        // GET: Jeweleries/Create
        public ActionResult Create()
        {
            ViewBag.FitID = new SelectList(db.Fits, "FitID", "FitName");
            ViewBag.InvID = new SelectList(db.InvStatus, "InvID", "InvName");
            ViewBag.MaterialID = new SelectList(db.Materials, "MaterialID", "MaterialName");
            ViewBag.SupplierID = new SelectList(db.Suppliers, "SupplierID", "CompanyName");
            ViewBag.TypeID = new SelectList(db.Types, "TypeID", "TypeName");
            return View();
        }

        // POST: Jeweleries/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ProductID,ProductName,MaterialID,FitID,InvID,TypeID,SupplierID,UnitsSold,ReleaseDate,ProductImage,Description,SoldAsPair,Price")] Jewelery jewelery, HttpPostedFileBase productCover)
        {
            if (ModelState.IsValid)
            {
                string file = "NoImage.jpg";

                if (productCover != null)
                {
                    file = productCover.FileName;
                    string ext = file.Substring(file.LastIndexOf('.'));
                    string[] goodExts =
                    {
                        ".jpg", ".jpeg", ".png", ".gif"
                    };
                    if (goodExts.Contains(ext.ToLower()) && productCover.ContentLength <= 4194304)
                    {
                        //create a new file name using GUID
                        file = Guid.NewGuid() + ext;

                        #region Resize Image
                        string savePath = Server.MapPath("~/Content/images/products/");
                        Image convertedImage = Image.FromStream(productCover.InputStream);

                        int maxImageSize = 500;
                        int maxThumbSize = 100;

                        ImageService.ResizeImage(savePath, file, convertedImage, maxImageSize, maxThumbSize);
                        #endregion
                    }



                }
                jewelery.ProductImage = file;//this for now needs to be outside the IF block, because it was manipulating the productCover / file
                //only. it wasn't even touching jewelery.ProductImage yet.

                db.Jeweleries.Add(jewelery);
                db.SaveChanges();
                return RedirectToAction("Index");

            }

            ViewBag.FitID = new SelectList(db.Fits, "FitID", "FitName", jewelery.FitID);
            ViewBag.InvID = new SelectList(db.InvStatus, "InvID", "InvName", jewelery.InvID);
            ViewBag.MaterialID = new SelectList(db.Materials, "MaterialID", "MaterialName", jewelery.MaterialID);
            ViewBag.SupplierID = new SelectList(db.Suppliers, "SupplierID", "CompanyName", jewelery.SupplierID);
            ViewBag.TypeID = new SelectList(db.Types, "TypeID", "TypeName", jewelery.TypeID);
            return View(jewelery);
        }

        // GET: Jeweleries/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Jewelery jewelery = db.Jeweleries.Find(id);
            if (jewelery == null)
            {
                return HttpNotFound();
            }
            ViewBag.FitID = new SelectList(db.Fits, "FitID", "FitName", jewelery.FitID);
            ViewBag.InvID = new SelectList(db.InvStatus, "InvID", "InvName", jewelery.InvID);
            ViewBag.MaterialID = new SelectList(db.Materials, "MaterialID", "MaterialName", jewelery.MaterialID);
            ViewBag.SupplierID = new SelectList(db.Suppliers, "SupplierID", "CompanyName", jewelery.SupplierID);
            ViewBag.TypeID = new SelectList(db.Types, "TypeID", "TypeName", jewelery.TypeID);
            return View(jewelery);
        }

        // POST: Jeweleries/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ProductID,ProductName,MaterialID,FitID,InvID,TypeID,SupplierID,UnitsSold,ReleaseDate,ProductImage,Description,SoldAsPair,Price")] Jewelery jewelery, HttpPostedFileBase productImage)//so the first productImage is the hiddenfor, then the input is this httppostedfilebase.

        {
            if (ModelState.IsValid)
            {
                #region file upload
                string file = jewelery.ProductImage;
                if (productImage != null)
                {
                    file = productImage.FileName;
                    string ext = file.Substring(file.LastIndexOf("."));//it knows to go to the very end since there is only the one param.
                    string[] goodExts =
                    {
                        ".jpeg", ".jpg", ".png", ".gif"
                    };
                    if (goodExts.Contains(ext.ToLower()) && productImage.ContentLength <= 4194304)//by default only 4mb.
                    {
                        file = Guid.NewGuid() + ext;//renaming the file name to a generate guid AND the ext we created.
                        #region resize image
                        string savePath = Server.MapPath("~/Content/images/products/");//map path gives us the file path for the certain environment.
                        Image ConvertedImage = Image.FromStream(productImage.InputStream);
                        int maxImageSize = 500;
                        int maxThumbSize = 100;
                        ImageService.ResizeImage(savePath, file, ConvertedImage, maxImageSize, maxThumbSize);
                        #endregion
                        if (jewelery.ProductImage != null && jewelery.ProductImage != "NoImage.jpg")//Noimage needs to be in products folder.
                        {
                            //if the image wasn't null, or was NoImage then:
                            ImageService.Delete(savePath, jewelery.ProductImage);
                        }
                        jewelery.ProductImage = file;
                    }


                }
                #endregion
                db.Entry(jewelery).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.FitID = new SelectList(db.Fits, "FitID", "FitName", jewelery.FitID);
            ViewBag.InvID = new SelectList(db.InvStatus, "InvID", "InvName", jewelery.InvID);
            ViewBag.MaterialID = new SelectList(db.Materials, "MaterialID", "MaterialName", jewelery.MaterialID);
            ViewBag.SupplierID = new SelectList(db.Suppliers, "SupplierID", "CompanyName", jewelery.SupplierID);
            ViewBag.TypeID = new SelectList(db.Types, "TypeID", "TypeName", jewelery.TypeID);
            return View(jewelery);
        }
        //AJAX DELETE STEP 2
        //// GET: Jeweleries/Delete/5
        //public ActionResult Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Jewelery jewelery = db.Jeweleries.Find(id);
        //    if (jewelery == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(jewelery);
        //}

        //// POST: Jeweleries/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public ActionResult DeleteConfirmed(int id)
        //{
        //    Jewelery jewelery = db.Jeweleries.Find(id);
        //    db.Jeweleries.Remove(jewelery);
        //    db.SaveChanges();
        //    return RedirectToAction("Index");
        //}

            //AJAX DELETE STEP 9 - Delete. Delete a jewelery record and return ONLY JSON data. Back to C# in a controller.
            [AcceptVerbs(HttpVerbs.Post)]//validation
            public JsonResult AjaxDelete(int id)//JsonResult is used to send Json-formatted content as a response.
        {
            Jewelery jewelery = db.Jeweleries.Find(id);//here jewelery is an object of jewelery class, and it equals the Jeweleries in the DB with the id we are seeking for the delete.
            db.Jeweleries.Remove(jewelery);//removes jewelery that was declared above that has the id we are seeking to delete. 
            db.SaveChanges();

StoreFront2.UI.MVC/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<hgroup>
    <h2>@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>
</hgroup>
<div class="row-fluid">
    <div class="span12">
        <p>Use this area to provide additional information.</p>
    </div>
</div>

StoreFront2.UI.MVC/Views/Home/Cart.cshtml
@{
    ViewBag.Title = "Cart";
}

<div class="colorlib-product">
    <div class="container">
        <div class="row row-pb-lg">
            <div class="col-md-10 offset-md-1">
                <div class="process-wrap">
                    <div class="process text-center active">
                        <p><span>01</span></p>
                        <h3>Shopping Cart</h3>
                    </div>
                    <div class="process text-center">
                        <p><span>02</span></p>
                        <h3>Checkout</h3>
                    </div>
                    <div class="process text-center">
                        <p><span>03</span></p>
                        <h3>Order Complete</h3>
                    </div>
                </div>
            </div>
        </div>
        <div class="row row-pb-lg">
            <div class="col-md-12">
                <div class="product-name d-flex">
                    <div class="one-forth text-left px-4">
                        <span>Product Details</span>
                    </div>
                    <div class="one-eight text-center">
                        <span>Price</span>
                    </div>
                    <div class="one-eight text-center">
                        <span>Quantity</span>
                    </div>
                    <div class="one-eight text-center">
                        <span>Total</span>
                    </div>
                    <div class="one-eight text-center px-4">
                        <span>Remove</span>
                    </div>
                </div>
                <div class="product-cart d-flex">
                    <div class="one-forth">
                        <div class="product-img" style="background-image: url(./images/item-6.jpg);">
                        </div>
                        <div class="display-tc">
                            <h3>Product Name</h3>
                        </div>
                    </div>
                    <div class="one-eight text-center">
                        <div class="display-tc">
                            <span class="price">$68.00</span>
                        </div>
                    </div>
                    <div class="one-eight text-center">
                        <div class="display-tc">
                            <input type="text" id="quantity" name="quantity" class="form-control input-number text-center" value="1" min="1" max="100">
                        </div>
                    </div>
                    <div class="one-eight text-center">
                        <div class="display-tc">
                            <span class="price">$120.00</span>
                        </div>
                    </div>
                    <div class="one-eight text-center">
                        <div class="display-tc">
                            <a href="#" class="closed"></a>
                        </div>
                    </div>
                </div>
                <div class="product-cart d-flex">
                    <div class="one-forth">
                        <div class="product-img" style="background-image: url(./images/item-7.jpg);">
                        </div>
                        <div class="display-tc">
                            <h3>Product Name</h3>
                        </div>
                    </div>
                    <div class="one-eight text-center">
                        <div class="display-tc">
                            <span class="price">$68.00</span>
                        </div>
                    </div>
                    <div class="one-eight text-center">
                        <div class="display-tc">
                            <form action="#">
                                <input type="text" name="quantity" class="form-control input-number text-center" value="1" min="1" max="100">
                            </form>
                        </div>
                    </div>
                    <div class="one-eight text-center">
                        <div class="display-tc">
                            <span class="price">$120.00</span>
                        </div>
                    </div>
                    <div class="one-eight text-center">
                        <div class="display-tc">
                            <a href="#" class="closed"></a>
                        </div>
                    </div>
                </div>
                <div class="product-cart d-flex">
                    <div class="one-forth">
                        <div class="product-img" style="background-image: url(./images/item-8.jpg);">
                        </div>
                        <div class="display-tc">
                            <h3>Product Name</h3>
                        </div>
                    </div>
                    <div class="one-eight text-center">
                        <div class="display-tc">
                            <span class="price">$68.00</span>
                        </div>
                    </div>
                    <div class="one-eight text-center">
                        <div class="display-tc">
                            <input type="text" id="quantity" name="quantity" class="form-control input-number text-center" value="1" min="1" max="100">
                        </div>
                    </div>
                    <div class="one-eight text-center">
                        <div class="display-tc">
                            <span class="price">$120.00</span>
                        </div>
                    </div>
                    <div class="one-eight text-center">
                        <div class="display-tc">
                            <a href="#" class="closed"></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row row-pb-lg">
            <div class="col-md-12">
                <div class="total-wrap">
                    <div class="row">
                        <div class="col-sm-8">
                            <form action="#">
                                <div class="row form-group">
                                    <div class="col-sm-9">
                                        <!--<input type="text" name="quantity" class="form-control input-number" placeholder="Your Coupon Number...">-->
                                    </div>
                                    <div class="col-sm-3">
                                        <!--<input type="submit" value="Apply Coupon" class="btn btn-primary">-->
                                    </div>
                                </div>
                            </form>
                        </div>
                        <div class="col-sm-4 text-center">
                            <div class="total">
                                <div class="sub">
                                    <p><span>Subtotal:</span> <span>$200.00</span></p>
                                    <p><span>Delivery:</span> <span>$0.00</span></p>
                                    <p><span>Discount:</span> <span>$45.00</span></p>
                                </div>
                                <div class="grand-total">
                                    <p><span><strong>Total:</strong></span> <span>$450.00</span></p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

StoreFront2.UI.MVC/Views/Home/EmailConfirmation.cshtml
@model StoreFrontJordan.MVC.UI.Models.ContactViewModel

@{
    ViewBag.Title = "Your Email Confirmation";
}

<h2>@ViewBag.Title</h2>

<div>

    <hr />
    <div class="row">
        <div class="col-md-offest-3 col-md-6">
            <p class="text-success">
                We have received your email, @Model.Name. Within 24 hours, we will contact you at @Model.Message in regards to the following message:
            </p>
        </div>
    </div>
</div>

<p>
    @*@Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
        @Html.ActionLink("Back to List", "Index")*@
</p>

StoreFront2.UI.MVC/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

		
<aside id="colorlib-hero">
    <div class="flexslider">
        <ul class="slides">
            <li style="background-image: url(../../Content/images/flexSliderImg2.jpg);">
                <div class="overlay"></div>
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-sm-6 offset-sm-3 text-center slider-text">
                            <div class="slider-text-inner">
                                <div class="desc">
                                    <img class="head-1" src="~/Content/images/TheLuminaryLogo.png" width="200" height="200"/>
                                    <h2 class="head-2">Based in</h2>
                                    <h2 class="head-3">Los Angeles</h2>
                                    <p class="category"><span>Grand Opening</span></p>
                                    <p><a href="@Url.Action("Index","Jeweleries")" class="btn btn-primary">Shop Collection</a></p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </li>
            <li style="background-image: url(../../Content/images/mosaic2.jpg);">
                <div class="overlay"></div>
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-sm-6 offset-sm-3 text-center slider-text">
                            <div class="slider-text-inner">
                                <div class="desc">
                                    <h1 class="head-1">Spring</h1>
                                    <h2 class="head-2">2021</h2>
                                    <h2 class="head-3">Collection</h2>
                                    <p class="category"><span></span></p>
                                    <p><a href="@Url.Action("Index","Jeweleries")" class="btn btn-primary">Shop Collection</a></p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </li>
            <li style="background-image: url('../../Content/images/flexSliderImg (1).jpg');">
                <div class="overlay"></div>
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-sm-6 offset-sm-3 text-center slider-text">
                            <div class="slider-text-inner">
                                <div class="desc">
                                    <h1 class="head-1">Styles</h1>
                                    <h2 class="head-2">For</h2>
                                    <h2 class="head-3">Every <strong class="font-weight-bold">Season</strong></h2>
                                    <p class="category"><span></span></p>
                                    <p><a href="@Url.Action("Index","Jeweleries")" class="btn btn-primary">Shop Collection</a></p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </li>
        </ul>
    </div>
</aside>
<div class="container" id="home">
    <div class="row" id="welcomeContainer">
        <div class="col-12 text-center" id="welcome">
           

            <h2>Welcome to The Luminary Body Jewelery</h2>
            <p>Bringing to you various selections of alternative styles in quality and unique materials. Step outside the conventional, allow yourself to stand out, and ride your wave. Take charge of your look. </p>
            <p>With trusted suppliers we have curated a collection for you year round. Always check back and lean on us for the trending styles. </p>

        </div>
    </div>
</div>
<div class="colorlib-featured">
    <div class="container">
        <div class="row">
            <div class="col-sm-4 text-center">
                <div class="featured">
                    <div class="featured-img featured-img-2" style="background-image:url('../../Content/images/ourahalfmoonplugs1.jpg') ;">
                        <h2>Plugs</h2>
                        <p><a href="@Url.Action("Index","Jeweleries")" class="btn btn-primary btn-lg">Shop now</a></p>
                    </div>
                </div>
            </div>
            <div class="col-sm-4 text-center">
                <div class="featured">
                    <div class="featured-img featured-img-2" style="background-image:url('../../Content/images/SkullHangerGold1.jpg') ;">
                        <h2>Hangers</h2>
                        <p><a href="@Url.Action("Index","Jeweleries")" class="btn btn-primary btn-lg">Shop now</a></p>
                    </div>
                </div>
            </div>
            <div class="col-sm-4 text-center">
                <div class="featured">
                    <div class="featured-img featured-img-2" style="background-image: url('../../Content/images/LuminarySeptumClicker1.jpg');">
                        <h2>Clickers</h2>
                        <p><a href="@Url.Action("Index","Jeweleries")" class="btn btn-primary btn-lg">Shop now</a></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


@*<div class="container" id="home">
    <div class="row">

        <div class="col-12" id="home">

            <ul class="gallery-slideshow ">
                <li>
                    <img src="~/Content/images/item-3.jpg" />
                </li>

                <li>
                    <img src="~/Content/images/item-2.jpg" />
                </li>

                <li>
                    <img src="~/Content/images/item-5.jpg" />
                </li>

                <li>
                    <img src="~/Content/images/item-8.jpg" />
                </li>

                <li>
                    <img src="~/Content/images/item-9.jpg" />
                </li>

                <li>
                    <img src="~/Content/images/item-11.jpg" />
                </li>
            </ul>
        </div>


    </div>
</div>*@





@section scripts {
    <script>
        $(function () {
            $('.gallery-slideshow').slideshow({
                // default: 2000
                interval: 7000,
                // default: 500
                width: 499,
                // default: 350
                height: 499

            });
        });
    </script>


}